CREATE TABLE users(
                      id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      username varchar(30) NOT NULL ,
                      password NOT NULL,
                      full_name varchar(100),
                      email varchar(100) UNIQUE NOT NULL ,
                      bio varchar(1000)
)

